# Generated by Django 4.1.7 on 2023-09-05 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('title', models.CharField(max_length=255, verbose_name='Color title')),
                ('code', models.CharField(max_length=255, verbose_name='Color code')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('title', models.CharField(default=None, max_length=128, null=True, verbose_name='Title')),
                ('by_percentage', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Percentage')),
                ('valid_until', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Valid until')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('title', models.CharField(max_length=255, verbose_name='Field type title')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=128, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/icons/', verbose_name='Image')),
                ('description', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wms.productcategory')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
            },
        ),
        migrations.CreateModel(
            name='ProductCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Image')),
                ('tag', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Tag')),
                ('bar_qr_code', models.CharField(blank=True, default=None, max_length=256, null=True, unique=True, verbose_name='Product code')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
                ('categories', models.ManyToManyField(blank=True, default=None, related_name='categories', to='wms.productcategory', verbose_name='Category')),
                ('color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.color')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Core',
                'verbose_name_plural': 'Product List',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=24, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Base Product unit',
                'verbose_name_plural': 'Base Product units',
                'db_table': 'wms_productunit',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StockInProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('reason', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Income reason')),
                ('count', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Quantity')),
                ('actual_quantity', models.PositiveIntegerField(blank=True, default=None, help_text='Leave empty if you want to set it equal to quantity', null=True, verbose_name='Actual quantity')),
                ('custom_barcode', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Custom barcode')),
                ('income_price', models.FloatField(blank=True, default=None, null=True, verbose_name='Income price')),
                ('whole_price', models.FloatField(blank=True, default=None, null=True, verbose_name='Whole price')),
                ('single_price', models.FloatField(verbose_name='Single price')),
                ('currency', models.SmallIntegerField(choices=[(1, 'Sum'), (2, 'Dollar'), (3, 'Euro')], default=1)),
                ('payment_method', models.SmallIntegerField(choices=[(0, 'All'), (1, 'Cash'), (2, 'Transfer money')], default=1)),
                ('markup', models.SmallIntegerField(blank=True, default=0, verbose_name='Markup')),
                ('session', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Session')),
                ('income_date', models.DateField(blank=True, default=None, null=True, verbose_name='Income date')),
                ('vat', models.PositiveIntegerField(blank=True, choices=[(1, 0), (2, 15)], default=1, verbose_name='VAT')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_product_created_by', to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.discount', verbose_name='Discount')),
                ('from_organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.organization', verbose_name='Origin')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wms.productcore', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product income transaction',
                'verbose_name_plural': 'Product income transactions',
            },
        ),
        migrations.CreateModel(
            name='StockProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='images', verbose_name='Image')),
                ('caption', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Caption')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_product_image', to='wms.stockinproduct', verbose_name='StockInProduct')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
            },
        ),
        migrations.CreateModel(
            name='StockProductExtraFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=128, null=True, verbose_name='Title')),
                ('value', models.CharField(blank=True, default='', max_length=2048, verbose_name='Value')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_product_extra_fields', to='wms.stockinproduct', verbose_name='StockInProduct')),
            ],
            options={
                'verbose_name': 'Product extra field',
                'verbose_name_plural': 'Product extra fields',
            },
        ),
        migrations.CreateModel(
            name='StockPoint3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('title', models.CharField(default=None, max_length=512, null=True, verbose_name='Stock Point')),
                ('description', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Description')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
                ('address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.organizationaddress')),
                ('assigned_director', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_point_assigned_director', to='crm.person')),
                ('belongs_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.organization')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Point.',
                'verbose_name_plural': 'Stock Points',
            },
        ),
        migrations.AddField(
            model_name='stockinproduct',
            name='stock_point',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.stockpoint3'),
        ),
        migrations.AddField(
            model_name='stockinproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_product_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductUnitConverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('title', models.CharField(default=None, max_length=24, null=True, verbose_name='Unit title')),
                ('conversion_rate', models.FloatField(default=None, help_text='Conversion rate to base unit', max_length=24, null=True, verbose_name='Conversion Rate')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wms.stockinproduct', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product unit converter',
                'verbose_name_plural': 'Product unit converters',
                'db_table': 'wms_productunitconverter',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('title', models.CharField(default=None, max_length=128, null=True, verbose_name='key')),
                ('value', models.CharField(default='', max_length=2048, verbose_name='Value')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_core', to='wms.productcore', verbose_name='Product')),
                ('product_field_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.fieldtype')),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('image', models.ImageField(null=True, upload_to='product_core_images', verbose_name='Image')),
                ('sequence', models.IntegerField(null=True, unique=True, verbose_name='Sequence')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_core_image', to='wms.productcore', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productcore',
            name='unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.productunit', verbose_name='Product unit'),
        ),
        migrations.AddField(
            model_name='productcore',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('title', models.CharField(default=None, max_length=128, null=True, verbose_name='Title')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stockinproduct',
            unique_together={('product', 'session')},
        ),
    ]
