# Generated by Django 3.1.7 on 2021-03-21 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('count', models.PositiveIntegerField(verbose_name='Quantity')),
                ('income_price', models.FloatField(verbose_name='Income price')),
                ('whole_price', models.FloatField(verbose_name='Whole price')),
                ('single_price', models.FloatField(verbose_name='Single price')),
                ('session', models.CharField(max_length=128, verbose_name='Session')),
                ('income_date', models.DateField(verbose_name='Income date')),
                ('vat', models.PositiveIntegerField(choices=[(1, 0), (2, 15)], default=1, verbose_name='VAT')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_product_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('description', models.CharField(default='', max_length=2048, verbose_name='Description')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_core_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product detail',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=128, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Description')),
                ('bar_qr_code', models.CharField(default=None, max_length=256, null=True, unique=True, verbose_name='Product code')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
                ('categories', models.ManyToManyField(to='wms.ProductCategory', verbose_name='Category')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField(verbose_name='Product fields json')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=24, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('title', models.CharField(default=None, max_length=512, null=True, verbose_name='Warehouse')),
                ('description', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Description')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
                ('address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.address')),
                ('belongs_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.organization')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WmsIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('reason', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Income reason')),
                ('currency', models.SmallIntegerField(choices=[(1, 'Sum'), (2, 'Dollar'), (3, 'Euro')], default=1)),
                ('payment_method', models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Transfer money')], default=1)),
                ('markup', models.SmallIntegerField(blank=True, default=0, verbose_name='Markup')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_created_by', to=settings.AUTH_USER_MODEL)),
                ('from_organization', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.organization')),
                ('products', models.ManyToManyField(to='wms.IncomingProduct', verbose_name='products')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_updated_by', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('hint', models.CharField(max_length=256, verbose_name='Hint')),
                ('description', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Description')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_image_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_image_product', to='wms.productcore', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_image_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('value', models.CharField(default='', max_length=2048, verbose_name='Value')),
                ('product_field_type', models.SmallIntegerField(choices=[(1, 'Text'), (2, 'Currency'), (3, 'Decimal')], default=1, verbose_name='Field type')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wms.product', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='productcore',
            name='unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.productunit', verbose_name='Product unit'),
        ),
        migrations.AddField(
            model_name='productcore',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_core_income', to='wms.productcore', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_core_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('price', models.FloatField(verbose_name='Price')),
                ('currency', models.SmallIntegerField(choices=[(1, 'Sum'), (2, 'Dollar'), (3, 'Euro')], default=1)),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Activated')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_list_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wms.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_list_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='incomingproduct',
            name='product',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='wms.productcore', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='incomingproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_product_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
