# Generated by Django 3.2 on 2022-05-15 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductDetails',
        ),
        migrations.AlterModelOptions(
            name='productcore',
            options={'verbose_name': 'Product Core', 'verbose_name_plural': 'Product Core'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='hint',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Hint'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product_images/', verbose_name='Image'),
        ),
    ]
