# Generated by Django 4.1.7 on 2023-09-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_alter_stockinproduct_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockinproduct',
            table='products_in_stock',
        ),
    ]
