# Generated by Django 4.1.7 on 2023-03-07 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_role_organizationemployee_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0002_alter_color_created_by_alter_color_updated_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockPoint3',
            new_name='StockPoint',
        ),
    ]
