# Generated by Django 3.2 on 2022-05-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_auto_20220515_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfield',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wms.productcore', verbose_name='Product'),
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
