# Generated by Django 3.2 on 2022-05-15 18:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0003_auto_20220515_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncomingProduct',
            new_name='Stock',
        ),
    ]
