# Generated by Django 4.1.7 on 2023-03-07 17:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_role_organizationemployee_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0003_rename_stockpoint3_stockpoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockPoint',
            new_name='StockPoint3',
        ),
    ]
