# Generated by Django 3.2 on 2022-05-15 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_organization_logo'),
        ('wms', '0005_rename_stock_stockproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproduct',
            name='currency',
            field=models.SmallIntegerField(choices=[(1, 'Sum'), (2, 'Dollar'), (3, 'Euro')], default=1),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='from_organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.organization', verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='markup',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Markup'),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Transfer money')], default=1),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Income reason'),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='warehouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.warehouse'),
        ),
        migrations.DeleteModel(
            name='WmsIncome',
        ),
    ]
