# Generated by Django 4.1.7 on 2023-09-06 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_remove_mergedproductsinstock_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedproductsinstock',
            name='product',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='wms.productcore', unique=True, verbose_name='Product'),
        ),
    ]
