# Generated by Django 4.1.7 on 2023-03-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_productfield_created_by_productfield_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='updated_date',
        ),
    ]
