# Generated by Django 4.1.7 on 2023-09-06 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_alter_mergedproductsinstock_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergedproductsinstock',
            name='id',
        ),
        migrations.AlterField(
            model_name='mergedproductsinstock',
            name='product',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wms.productcore', unique=True, verbose_name='Product'),
        ),
    ]
