# Generated by Django 3.2 on 2022-05-16 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_organization_address'),
        ('wms', '0006_auto_20220515_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockproduct',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stock'},
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='from_organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.organization', verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='warehouse',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.warehouse'),
        ),
    ]
