# Generated by Django 4.1.7 on 2023-09-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0007_remove_mergedproductsinstock_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedproductsinstock',
            name='actual_quantity',
            field=models.IntegerField(default=0, null=True, verbose_name='Actual quantity'),
        ),
        migrations.AlterField(
            model_name='mergedproductsinstock',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Total quantity'),
        ),
    ]
