# Generated by Django 4.1.7 on 2023-09-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0008_alter_mergedproductsinstock_actual_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedproductsinstock',
            name='stock_point',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.stockpoint3'),
        ),
    ]
