# Generated by Django 3.2 on 2022-05-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0008_productcategory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
    ]
