# Generated by Django 4.1.7 on 2023-09-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0009_mergedproductsinstock_stock_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedproductsinstock',
            name='product',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wms.productcore', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='mergedproductsinstock',
            name='stock_point',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.stockpoint3'),
        ),
    ]
