# Generated by Django 4.1.7 on 2023-03-07 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0009_alter_color_created_date_alter_color_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='created_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime.now, editable=False, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime.now, editable=False, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime.now, editable=False, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='created_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime.now, editable=False, verbose_name='Created date'),
        ),
    ]
