# Generated by Django 4.1.7 on 2023-09-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0010_alter_mergedproductsinstock_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedproductsinstock',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mergedproductsinstock',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wms.productcore', verbose_name='Product'),
        ),
    ]
