# Generated by Django 3.2 on 2022-06-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0010_productcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcore',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, related_name='categories', to='wms.ProductCategory', verbose_name='Category'),
        ),
    ]
