# Generated by Django 3.2 on 2022-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0011_alter_productcore_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcore',
            name='bar_qr_code',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, unique=True, verbose_name='Product code'),
        ),
    ]
