# Generated by Django 3.2 on 2022-07-01 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0012_alter_productcore_bar_qr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product image', 'verbose_name_plural': 'Product images'},
        ),
        migrations.AlterModelOptions(
            name='stockproduct',
            options={'verbose_name': 'Product income transaction', 'verbose_name_plural': 'Product income transactions'},
        ),
        migrations.AlterField(
            model_name='productfield',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_core', to='wms.productcore', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='StockProductExtraFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('value', models.CharField(default='', max_length=2048, verbose_name='Value')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_product_extra_fields', to='wms.stockproduct', verbose_name='StockProduct')),
            ],
        ),
    ]
