# Generated by Django 4.1.7 on 2023-09-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0012_alter_mergedproductsinstock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mergedproductsinstock',
            options={'verbose_name': 'My products', 'verbose_name_plural': 'My products list'},
        ),
    ]
