# Generated by Django 3.2 on 2022-07-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0013_auto_20220701_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
