# Generated by Django 3.2 on 2022-07-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0014_delete_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproductextrafields',
            name='filed',
            field=models.ManyToManyField(blank=True, default=None, related_name='subfields', to='wms.StockProductExtraFields', verbose_name='Field'),
        ),
    ]
