# Generated by Django 4.1.7 on 2023-09-08 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0014_mergedproductsinstock_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedproductsinstock',
            name='stock_point',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.stockpoint3'),
        ),
    ]
