# Generated by Django 4.1.7 on 2023-09-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0015_alter_mergedproductsinstock_stock_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedproductsinstock',
            name='actual_quantity',
            field=models.FloatField(default=0, null=True, verbose_name='Actual quantity'),
        ),
        migrations.AlterField(
            model_name='mergedproductsinstock',
            name='total_quantity',
            field=models.FloatField(default=0, null=True, verbose_name='Total quantity'),
        ),
        migrations.AlterField(
            model_name='stockinproduct',
            name='actual_quantity',
            field=models.FloatField(blank=True, default=None, help_text='Leave empty if you want to set it equal to quantity', null=True, verbose_name='Actual quantity'),
        ),
        migrations.AlterField(
            model_name='stockinproduct',
            name='count',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Quantity'),
        ),
    ]
