# Generated by Django 3.2 on 2022-07-01 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0015_stockproductextrafields_filed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproductextrafields',
            name='filed',
        ),
        migrations.AddField(
            model_name='stockproductextrafields',
            name='filed',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subfield', to='wms.stockproductextrafields', verbose_name='Field'),
        ),
    ]
