# Generated by Django 4.1.7 on 2023-10-03 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0016_alter_mergedproductsinstock_actual_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproductimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_product_image', to='wms.mergedproductsinstock', verbose_name='MergedProductsInStock'),
        ),
    ]
