# Generated by Django 3.2 on 2022-07-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0016_auto_20220701_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProductExtraFieldSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128, null=True, verbose_name='Section name')),
            ],
        ),
        migrations.RemoveField(
            model_name='stockproductextrafields',
            name='filed',
        ),
        migrations.AddField(
            model_name='stockproductextrafields',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_product_extra_fields_section', to='wms.stockproductextrafieldsection', verbose_name='Section'),
        ),
    ]
