# Generated by Django 3.2 on 2022-07-02 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0017_auto_20220701_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockproductextrafields',
            options={'verbose_name': 'Product extra field', 'verbose_name_plural': 'Product extra fields'},
        ),
        migrations.AlterModelOptions(
            name='stockproductextrafieldsection',
            options={'verbose_name': 'Product extra fields section', 'verbose_name_plural': 'Product extra fields sections'},
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='income_price',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Income price'),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(1, 'Cash'), (2, 'Transfer money')], default=1),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='vat',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 0), (2, 15)], default=1, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='whole_price',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Whole price'),
        ),
        migrations.AlterField(
            model_name='stockproductextrafields',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stock_product_extra_fields_section', to='wms.stockproductextrafieldsection', verbose_name='Section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockproductextrafields',
            name='title',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stockproductextrafields',
            name='value',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Value'),
        ),
    ]
