# Generated by Django 4.1.7 on 2023-03-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0017_alter_color_created_by_alter_color_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images', verbose_name='Image')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_product_image', to='wms.stockproduct', verbose_name='StockProduct')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
            },
        ),
    ]
