# Generated by Django 3.2 on 2022-07-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0018_auto_20220702_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproductextrafields',
            name='section',
        ),
        migrations.DeleteModel(
            name='StockProductExtraFieldSection',
        ),
    ]
