# Generated by Django 4.1.7 on 2023-03-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0018_stockproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproductimage',
            name='caption',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Caption'),
        ),
    ]
