# Generated by Django 3.2 on 2022-07-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0019_auto_20220702_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfield',
            name='key',
            field=models.CharField(verbose_name='key', max_length=128, blank=False, default=None, null=True),
        ),
    ]
