# Generated by Django 4.1.7 on 2023-03-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0019_stockproductimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproduct',
            name='images',
        ),
        migrations.AlterField(
            model_name='stockproductimage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
