# Generated by Django 3.2 on 2022-07-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0020_remove_productfield_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfield',
            name='key',
        ),
        migrations.RemoveField(
            model_name='productfield',
            name='title',
        ),
    ]
