# Generated by Django 4.1.7 on 2023-06-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0020_remove_stockproduct_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcore',
            name='image',
        ),
        migrations.AddField(
            model_name='productcore',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Image'),
        ),
    ]
