# Generated by Django 3.2 on 2022-07-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0021_auto_20220702_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfield',
            name='title',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='key'),
        ),
    ]
