# Generated by Django 4.1.7 on 2023-06-14 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0021_remove_productcore_image_productcore_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='product_core_images', verbose_name='Image')),
                ('sequence', models.IntegerField(null=True, unique=True, verbose_name='Sequence')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_core_image', to='wms.productcore', verbose_name='Product')),
            ],
        ),
    ]
