# Generated by Django 4.1.7 on 2023-06-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0023_productcoreimage_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
