# Generated by Django 4.1.7 on 2023-09-05 04:45

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('street', models.CharField(max_length=128, verbose_name='Street')),
                ('zip_code', models.PositiveIntegerField(verbose_name='Zip code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SmallIntegerField(default=1, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tint_color', models.CharField(default='#000000', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('name', models.CharField(max_length=256, verbose_name='Bank name')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Country name')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('is_active', models.BooleanField(default=True)),
                ('card_number', models.CharField(default=None, max_length=255, null=True)),
                ('points', models.IntegerField(default=0)),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeCareerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_working', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created date')),
                ('name', models.CharField(max_length=512, verbose_name='File name')),
                ('file', models.FileField(default=None, upload_to='', verbose_name='File')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated date')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('logo', models.ImageField(null=True, upload_to='organization_logo', verbose_name='Logo')),
                ('banner_image', models.ImageField(null=True, upload_to='organization_banner', verbose_name='Banner image')),
                ('tint_color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('#[0-9A-Fa-f]{6}')], verbose_name='Color')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('legal_name', models.CharField(max_length=512, null=True, verbose_name='Legal name')),
                ('description', models.CharField(default=None, max_length=2048, null=True, verbose_name='Description')),
                ('organization_type', models.PositiveSmallIntegerField(choices=[(1, 'Организация'), (2, 'Физическое лицо')], default=1, verbose_name='Organization type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.CharField(max_length=128, verbose_name='Building number')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
            ],
            options={
                'verbose_name': 'Organization address',
                'verbose_name_plural': 'Organization addresses',
            },
        ),
        migrations.CreateModel(
            name='OrganizationEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('user', models.CharField(db_index=True, default=None, max_length=255, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Province name')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('country', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.country', verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Region/City name')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('province', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.province', verbose_name='Province')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('is_business', models.BooleanField(default=False, verbose_name='Is business')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
