# Generated by Django 4.1.7 on 2023-03-05 07:12

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='bannerImage',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='crm.organizationaddress'),
        ),
        migrations.AddField(
            model_name='organization',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='organization_banner', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='bank',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='crm.bank', verbose_name='Banks'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='crm.person', verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default=datetime.date(2023, 3, 5), max_length=512, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Организация'), (2, 'Физическое лицо')], default=1, verbose_name='Organization type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tint_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('#[0-9A-Fa-f]{6}')], verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='crm.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='memberships',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='crm.organizationmembership'),
        ),
    ]
