# Generated by Django 4.1.7 on 2023-03-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_organization_bannerimage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationMembership',
            new_name='OrganizationEmployee',
        ),
    ]
