# Generated by Django 4.1.7 on 2023-09-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=128, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=17, null=True, verbose_name='Phone number'),
        ),
    ]
