# Generated by Django 4.1.7 on 2023-09-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_person_address_person_email_person_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='person_avatar', verbose_name='Avatar'),
        ),
    ]
