# Generated by Django 3.2 on 2022-05-16 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.address'),
        ),
    ]
