# Generated by Django 3.2 on 2022-05-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_organization_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.region', verbose_name='Region'),
        ),
    ]
