# Generated by Django 4.1.7 on 2023-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_person_created_by_alter_person_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_business',
            field=models.BooleanField(default=False, verbose_name='Is business'),
        ),
    ]
