# Generated by Django 3.2 on 2022-05-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_address_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Организация'), (2, 'Физическое лицо')], default=1, verbose_name='Organization type'),
        ),
        migrations.AlterField(
            model_name='region',
            name='province',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.province', verbose_name='Province'),
        ),
    ]
