# Generated by Django 4.1.7 on 2023-09-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_client_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('user', 'organization')},
        ),
    ]
