# Generated by Django 3.2 on 2022-05-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20220516_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='bank',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='company_bank_list', to='crm.Bank', verbose_name='Bank list'),
        ),
    ]
