# Generated by Django 4.1.7 on 2023-03-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_address_created_by_address_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Updated date'),
        ),
    ]
