# Generated by Django 3.2 on 2022-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_organization_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bank',
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(null=True, upload_to='organization_logo', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default=None, max_length=512, null=True, unique=True, verbose_name='name'),
        ),
    ]
