# Generated by Django 4.1.7 on 2023-09-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_client_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerCard',
        ),
    ]
