# Generated by Django 4.1.7 on 2023-09-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_delete_customercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
