# Generated by Django 4.1.7 on 2023-03-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_address_created_by_alter_address_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_date',
            field=models.DateTimeField(auto_created=True, blank=True, editable=False, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_date',
            field=models.DateTimeField(auto_created=True, blank=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(auto_created=True, blank=True, editable=False, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_date',
            field=models.DateTimeField(auto_created=True, blank=True, verbose_name='Updated date'),
        ),
    ]
