# Generated by Django 4.1.7 on 2023-03-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_address_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_date',
            field=models.DateTimeField(auto_created=True, blank=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(auto_created=True, blank=True, verbose_name='Created date'),
        ),
    ]
