# Generated by Django 4.2.13 on 2025-04-05 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_client_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salary Amount')),
                ('currency', models.SmallIntegerField(choices=[(1, 'Sum'), (2, 'Dollar'), (3, 'Euro')], default=1, verbose_name='Currency')),
                ('payment_period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=10, verbose_name='Payment Period')),
                ('start_date', models.DateField(help_text='Date when this salary rate becomes effective', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Date when this salary rate ends (leave blank if currently active)', null=True, verbose_name='End Date')),
                ('bonus_eligible', models.BooleanField(default=False, verbose_name='Eligible for Bonus')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='crm.organizationemployee')),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Salary',
                'verbose_name_plural': 'Employee Salaries',
                'ordering': ['-start_date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Attendance Date')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Check-in Time')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Check-out Time')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave')], default='PRESENT', max_length=10, verbose_name='Attendance Status')),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Working Hours')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='crm.organizationemployee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='crm.organization')),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Attendance',
                'verbose_name_plural': 'Employee Attendances',
                'ordering': ['-date', 'check_in_time'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
