# Generated by Django 4.1.7 on 2023-03-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_organizationemployee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationemployee',
            name='user',
            field=models.CharField(db_index=True, default=None, max_length=255, verbose_name='Username'),
        ),
    ]
