# Generated by Django 4.1.7 on 2023-03-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_customercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercard',
            name='by_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.organization'),
        ),
        migrations.AlterField(
            model_name='customercard',
            name='card_number',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
