# Generated by Django 4.1.7 on 2023-03-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_remove_customercard_by_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercard',
            name='by_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.organization'),
        ),
    ]
