# Generated by Django 4.1.7 on 2023-03-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_role_created_date_alter_role_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
