# Generated by Django 4.1.7 on 2023-03-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_role_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
