# Generated by Django 4.1.7 on 2023-03-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crm', '0026_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissons',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
