# Generated by Django 4.1.7 on 2023-03-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_role_permissons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissons',
        ),
    ]
