# Generated by Django 4.1.7 on 2023-03-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_remove_role_permissons'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, null=True),
        ),
    ]
