# Generated by Django 4.1.7 on 2023-03-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_role_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(max_length=512, null=True, verbose_name='Legal name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
    ]
