# Generated by Django 4.1.7 on 2023-03-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_organization_legal_name_alter_organization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='level',
        ),
    ]
