# Generated by Django 4.1.7 on 2023-03-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_remove_role_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='belongs_to',
        ),
    ]
