# Generated by Django 4.1.7 on 2023-03-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_organization_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationemployee',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='organizationemployee',
            name='start_date',
        ),
    ]
