# Generated by Django 4.1.7 on 2023-03-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_employeecareerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecareerlog',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
