# Generated by Django 4.1.7 on 2023-03-21 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_employeecareerlog_is_working'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecareerlog',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeecareerlog',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_log', to='crm.organization'),
        ),
        migrations.AddField(
            model_name='employeecareerlog',
            name='person',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_log', to='crm.person'),
        ),
    ]
