# Generated by Django 4.1.7 on 2023-03-22 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_userconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfig',
            name='related_organizations',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='related_organizations',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_config', to='crm.organization'),
        ),
    ]
