# Generated by Django 4.1.7 on 2023-03-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_remove_userconfig_related_organizations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfig',
            old_name='related_organizations',
            new_name='working_organization',
        ),
    ]
