# Generated by Django 4.1.7 on 2023-03-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_rename_related_organizations_userconfig_working_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserConfig',
        ),
    ]
