# Generated by Django 3.2 on 2022-09-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_active_until',
            field=models.DateTimeField(default=None, null=True, verbose_name='Is active until'),
        ),
    ]
