# Generated by Django 4.1.7 on 2023-09-13 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0016_alter_mergedproductsinstock_actual_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('quantity', models.FloatField(default=0, null=True, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Price')),
                ('vat', models.PositiveIntegerField(default=1, null=True, verbose_name='VAT')),
                ('payment_method', models.SmallIntegerField(default=1, null=True, verbose_name='Payment method')),
                ('markup', models.SmallIntegerField(default=0, null=True, verbose_name='Markup')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trade_product', to='wms.mergedproductsinstock')),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trade_session', to='sales.tradesession')),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'product', 'price', 'payment_method', 'markup')},
            },
        ),
    ]
