# Generated by Django 4.1.7 on 2023-09-15 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_client_card_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0016_alter_mergedproductsinstock_actual_quantity_and_more'),
        ('sales', '0003_trade_from_transaction_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trade',
            name='cashier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trade_cashier', to='crm.organizationemployee'),
        ),
        migrations.AddField(
            model_name='trade',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total amount'),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Trade date'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='payment_method',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='trade',
            name='from_transaction_id',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='markup',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='product',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='vat',
        ),
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Updated date')),
                ('created_date', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Created date')),
                ('quantity', models.FloatField(default=0, null=True, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trade_product', to='wms.stockinproduct')),
                ('trade', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='sales.trade')),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trade', 'product')},
            },
        ),
    ]
