# Generated by Django 4.1.7 on 2023-09-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_client_card_number'),
        ('sales', '0004_alter_trade_unique_together_trade_cashier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.client'),
        ),
    ]
