# Generated by Django 4.1.7 on 2023-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_trade_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Payment amount'),
        ),
    ]
