# Generated by Django 4.1.7 on 2023-06-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_news_created_at_remove_news_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/news/', verbose_name='Image'),
        ),
    ]
